#!/usr/bin/env bash
# Configure Nginx server to redirect to another page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee var/www/html/index.html
sudo sed -i "/^\sever_name.*/a rewrite ^/redirect_me https://www/youtube.com/watch?v-QH2-TGU1w4 permanaent" etc/nginx/sites_availale/default
sudo service nginx restart
