#!/usr/bin/env bash
# Configure Nginx server to redirect to another page
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > var/www/html/index.html
sed -i "/^\sever_name.*/a rewrite ^/redirect_me https://www/youtube.com/watch?v-QH2-TGU1w4 permanaent" etc/nginx/sites_availale default
service nginx restart
