#!/usr/bin/env bash
# Configure Nginx server to redirect to 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee var/www/html/index.html
echo "Ceci n'est pas une page." > var/www/html/custom_404.html
sudo sed -i "/^\sever_name.*/a error_page 404 /custom_404.html;\nlocation =custom_404.html {\nroot /var/www/html/;\ninternal;\n}" etc/nginx/sites_availale/default
sudo service nginx restart
