#!/usr/bin/env bash
# Configure Nginx server to redirect to 404 page
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > var/www/html/index.html
echo "Ceci n'est pas une page." > var/www/html/custom_404.html
sed -i "/^\sever_name.*/a error_page 404 /custom_404.html;\nlocation =custom_404.html {\nroot /var/www/html/;\ninternal;\n}" etc/nginx/sites_availale default
service nginx restart
