#!/usr/bin/env bash 
#creates a file containing its PID
# Script that displays to "To infinity and beyond" indefinitely
# Displays "I hate the kill command", on SIGTERM signal
# Displays "Y U no love me ?!", on SIGINT signal
# Deletes the file and terminates, on SIGQUIT signal

echo $$  > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	trap "echo \"I hate the kill command\" & rm /var/run/myscript.pid & exit" SIGTERM
	trap "echo \"Y U no love me?!\" & exit" SIGINT
	trap "rm /var/run/myscript.pid & exit" SIGQUIT
done
