#!/usr/bin/env bash
# the script to display "Best School" 10 times
# on 4th loop display "bad lusk"
# on 8th loop display "good luck"

i=0
while [ $i -le 9 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
