#!/usr/bin/env bash
# Run Apache on the container and 
# Return a page containing Hello Holberton when querying it
apt-get -y update
apt-get -y install apache2
echo "ServerName localhost" >> sudo tee -a /etc/apache2/sites-available/my_domain.conf
echo "Hello Holberton"
service apache2 start
